version: "3.9"
services:
  db:
    image: postgres:12.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=subscriptions
    ports:
      - ${DB_PORT:-5432}:5432
