name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: coursier/cache-action@v6
      - name: Validate project
        run: sbt validate
      - name: Publish Docker container
        env:
          JIB_TARGET_IMAGE_USERNAME: johnspade
          JIB_TARGET_IMAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: sbt publishDockerContainer
